DB_DRIVER: postgres
# DB_HOST: meu-postgres
DB_HOST: "204.216.131.14"
DB_PORT: 5433
DB_USER: root
DB_PASSWORD: root
DB_NAME: campus-connect-api
WEB_SERVER_PORT: "8000"
JWT_SECRET: secret
JWT_EXPERESIN: 300
