DB_DRIVER: postgres
# DB_HOST: meu-postgres
DB_HOST: "localhost"
DB_PORT: 5433
DB_USER: postgres
DB_PASSWORD: postgres
DB_NAME: campus_connect
WEB_SERVER_PORT: "8000"
JWT_SECRET: secret
JWT_EXPERESIN: 300
