// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/user": {
            "post": {
                "description": "Create User",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Create User",
                "parameters": [
                    {
                        "description": "User request created",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/resource.createAuthReq"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "User created successfully",
                        "schema": {
                            "$ref": "#/definitions/resource.createAuthResp"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/resource.errorResp"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/resource.errorResp"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/resource.errorResp"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/resource.errorResp"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/resource.errorResp"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "resource.createAuthReq": {
            "type": "object",
            "required": [
                "email",
                "name",
                "password",
                "permission"
            ],
            "properties": {
                "email": {
                    "description": "email realizado para fazer login",
                    "type": "string"
                },
                "name": {
                    "description": "name realizado para fazer login",
                    "type": "string"
                },
                "password": {
                    "description": "senha deve conter pelo menos 8 caracteres",
                    "type": "string",
                    "minLength": 8
                },
                "permission": {
                    "description": "permission deve ser um desses: 'student', 'teacher', 'admin', 'owner'",
                    "type": "string"
                }
            }
        },
        "resource.createAuthResp": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string"
                }
            }
        },
        "resource.errorResp": {
            "type": "object",
            "properties": {
                "error": {
                    "description": "refere diretamente ao erro",
                    "type": "string"
                },
                "message": {
                    "description": "referente a mensagem tratada do erro",
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAtuh": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "Header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:18080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Campus Connect API",
	Description:      "API for university",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
